# Use the Raspberry Pi Pico VS Code extension install (~/.pico-sdk)
# when PICO_SDK_PATH / Ninja / the ARM toolchain are not already set.

if (WIN32 AND DEFINED ENV{USERPROFILE})
    set(_PICO_HOME "$ENV{USERPROFILE}/.pico-sdk")
elseif (DEFINED ENV{HOME})
    set(_PICO_HOME "$ENV{HOME}/.pico-sdk")
endif()

function(_pico_latest_dir out_var glob)
    file(GLOB _cands LIST_DIRECTORIES true "${glob}")
    if (_cands)
        list(SORT _cands COMPARE NATURAL)
        list(REVERSE _cands)
        list(GET _cands 0 _latest)
        set(${out_var} "${_latest}" PARENT_SCOPE)
    endif()
endfunction()

if (_PICO_HOME AND EXISTS "${_PICO_HOME}")
    if (NOT PICO_SDK_PATH AND NOT DEFINED ENV{PICO_SDK_PATH})
        _pico_latest_dir(_sdk "${_PICO_HOME}/sdk/*")
        if (_sdk AND EXISTS "${_sdk}/pico_sdk_init.cmake")
            set(PICO_SDK_PATH "${_sdk}")
            message(STATUS "Using Pico SDK ${_sdk}")
        endif()
    endif()

    if (NOT PICO_TOOLCHAIN_PATH AND NOT DEFINED ENV{PICO_TOOLCHAIN_PATH})
        _pico_latest_dir(_tc "${_PICO_HOME}/toolchain/*")
        if (_tc AND EXISTS "${_tc}/bin")
            set(PICO_TOOLCHAIN_PATH "${_tc}")
            message(STATUS "Using Pico toolchain ${_tc}")
        endif()
    endif()

    if (NOT CMAKE_MAKE_PROGRAM)
        file(GLOB _ninjas "${_PICO_HOME}/ninja/*/ninja.exe")
        if (NOT _ninjas)
            file(GLOB _ninjas "${_PICO_HOME}/ninja/*/ninja")
        endif()
        if (_ninjas)
            list(SORT _ninjas COMPARE NATURAL)
            list(REVERSE _ninjas)
            list(GET _ninjas 0 _ninja)
            set(CMAKE_MAKE_PROGRAM "${_ninja}" CACHE FILEPATH "Ninja from Pico VS Code SDK")
            message(STATUS "Using Ninja ${_ninja}")
        endif()
    endif()

    # Prefer the 2.1.1 binary the 2.2.0 SDK asks for; avoid find_package
    # (CMake 4.x rejects the old picotoolTargets policy range).
    if (NOT PICO_PICOTOOL_EXE)
        foreach(_pt_ver 2.1.1 2.2.0-a4 2.2.0)
            set(_pt_exe "${_PICO_HOME}/picotool/${_pt_ver}/picotool/picotool.exe")
            if (NOT EXISTS "${_pt_exe}")
                set(_pt_exe "${_PICO_HOME}/picotool/${_pt_ver}/picotool/picotool")
            endif()
            if (EXISTS "${_pt_exe}")
                set(PICO_PICOTOOL_EXE "${_pt_exe}" CACHE FILEPATH "picotool from Pico VS Code SDK")
                message(STATUS "Using picotool ${PICO_PICOTOOL_EXE}")
                break()
            endif()
        endforeach()
    endif()

    if (NOT pioasm_DIR)
        file(GLOB _pios "${_PICO_HOME}/tools/*/pioasm/pioasmConfig.cmake")
        if (_pios)
            list(SORT _pios COMPARE NATURAL)
            list(REVERSE _pios)
            list(GET _pios 0 _pio)
            get_filename_component(_pio_dir "${_pio}" DIRECTORY)
            set(pioasm_DIR "${_pio_dir}" CACHE PATH "pioasm from Pico VS Code SDK")
            message(STATUS "Using pioasm ${_pio_dir}")
        endif()
    endif()
endif()
