#!/usr/bin/env python3
"""Generate a Vivado Tcl fragment listing VHDL sources under fpga/src.

VHDL-2008 files: put this on the first line of the source file:

  --VHDL2008

Usage (from this directory):
  python gen_vhdl_sources.py
  python gen_vhdl_sources.py --include-tb
  python gen_vhdl_sources.py --out vhdl_sources.tcl --src ../src
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

VHDL_EXTS = {".vhd", ".vhdl"}

# First line marker: --VHDL2008 (optional spaces / trailing comment text)
VHDL2008_FIRST_LINE_RE = re.compile(r"^\s*--\s*VHDL2008\b", re.IGNORECASE)

# Match common testbench naming used in this tree.
TB_NAME_RE = re.compile(
    r"(^tb_)"  # tb_foo.vhd
    r"|(_tb$)"  # foo_tb.vhd
    r"|(_test$)"  # foo_test.vhd
    r"|(\d*tb$)",  # mux_5tb.vhd / fooTB.vhd
    re.IGNORECASE,
)


def is_testbench(path: Path) -> bool:
    return bool(TB_NAME_RE.search(path.stem))


def is_vhdl_2008(path: Path) -> bool:
    """True if the first line is a --VHDL2008 marker comment."""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            first = fh.readline()
    except OSError:
        return False
    return bool(VHDL2008_FIRST_LINE_RE.match(first))


def collect_vhdl(src_root: Path, include_tb: bool) -> list[Path]:
    files = [
        p.resolve()
        for p in sorted(src_root.rglob("*"))
        if p.is_file() and p.suffix.lower() in VHDL_EXTS
    ]
    if include_tb:
        return files
    return [p for p in files if not is_testbench(p)]


def tcl_quote(path: Path) -> str:
    text = path.as_posix().replace("\\", "/")
    return "{" + text + "}"


def write_tcl(files: list[Path], out_path: Path, src_root: Path) -> None:
    vhdl93 = [f for f in files if not is_vhdl_2008(f)]
    vhdl08 = [f for f in files if is_vhdl_2008(f)]

    lines = [
        "# Auto-generated by gen_vhdl_sources.py — do not edit by hand.",
        f"# Source root: {src_root.resolve().as_posix()}",
        f"# File count: {len(files)}  (VHDL: {len(vhdl93)}, VHDL 2008: {len(vhdl08)})",
        "# Mark VHDL-2008 sources with first-line comment: --VHDL2008",
        "",
        "set _open_spec_vhdl_files [list \\",
    ]
    for f in files:
        lines.append(f"  {tcl_quote(f)} \\")
    lines.append("]")
    lines.append("")

    lines.append("set _open_spec_vhdl93_files [list \\")
    if vhdl93:
        for f in vhdl93:
            lines.append(f"  {tcl_quote(f)} \\")
    lines.append("]")
    lines.append("")

    lines.append("set _open_spec_vhdl2008_files [list \\")
    if vhdl08:
        for f in vhdl08:
            lines.append(f"  {tcl_quote(f)} \\")
    lines.append("]")
    lines.append("")

    lines.append("foreach _f ${_open_spec_vhdl_files} {")
    lines.append("  if {[llength [get_files -quiet $_f]] == 0} {")
    lines.append("    add_files -norecurse $_f")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("if {[llength ${_open_spec_vhdl93_files}] > 0} {")
    lines.append("  set_property FILE_TYPE {VHDL} [get_files ${_open_spec_vhdl93_files}]")
    lines.append("}")
    lines.append("if {[llength ${_open_spec_vhdl2008_files}] > 0} {")
    lines.append("  set_property FILE_TYPE {VHDL 2008} [get_files ${_open_spec_vhdl2008_files}]")
    lines.append("}")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--src",
        type=Path,
        default=here.parent / "src",
        help="Root directory to scan for .vhd/.vhdl (default: ../src)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=here / "vhdl_sources.tcl",
        help="Output Tcl fragment path (default: ./vhdl_sources.tcl)",
    )
    parser.add_argument(
        "--include-tb",
        action="store_true",
        help="Include testbench files (excluded by default)",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Print relative paths (mark VHDL-2008 with [2008])",
    )
    args = parser.parse_args()

    src_root = args.src.resolve()
    if not src_root.is_dir():
        raise SystemExit(f"Source directory not found: {src_root}")

    files = collect_vhdl(src_root, include_tb=args.include_tb)
    write_tcl(files, args.out.resolve(), src_root)

    n08 = sum(1 for f in files if is_vhdl_2008(f))
    print(
        f"Wrote {len(files)} VHDL file(s) "
        f"({n08} VHDL-2008) -> {args.out.resolve()}"
    )
    if args.list:
        for f in files:
            tag = " [2008]" if is_vhdl_2008(f) else ""
            print(f"{f.relative_to(src_root).as_posix()}{tag}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
